PS C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server> npm run dev
> lost-and-found-backend@1.0.0 dev
> nodemon server.js

[nodemon] 3.1.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node server.js`
\Cloudinary configured.
C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server\node_modules\passport-oauth2\lib\strategy.js:87
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server\node_modules\passport-oauth2\lib\strategy.js:87:34)
    at new Strategy (C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server\node_modules\passport-google-oauth20\lib\strategy.js:52:18)
    at module.exports (C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server\config\passport.js:6:5)
    at Object.<anonymous> (C:\Users\M0N5TER\OneDrive\Desktop\LostAndFound\LostandFound\server\server.js:22:1)
    at Module._compile (node:internal/modules/cjs/loader:1730:14)
    at Object..js (node:internal/modules/cjs/loader:1895:10)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)

Node.js v22.15.0
[nodemon] app crashed - waiting for file changes before starting...
"still giving this error, fix this ."
# This is a .env file for the Lost and Found application.
GOOGLE_GENAI_API_KEY=AIzaSyD6PRzMCR3ZWMaB4kgxuPNDB_RiMSskdP0
MONGODB_URI=mongodb://localhost:27017/lostandfound
JWT_SECRET=sagar kumar shrivastav secket key
NEXT_PUBLIC_APP_URL=http://localhost:9002
PORT=5000
NODE_ENV=development
JWT_EXPIRES_IN=1h
GOOGLE_CLIENT_ID=331821321224-6p209pjjplrpe203ot273i5vqou0i32i.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
GOOGLE_CALLBACK_URL=http://localhost:5000/api/auth/google/callback
CLOUDINARY_CLOUD_NAME=LostAndFound
CLOUDINARY_API_KEY=983691725755663
CLOUDINARY_API_SECRET=YeBVaFE-RfLwv76z2lljNw-3d4k
CLIENT_URL=http://localhost:9002
NEXT_PUBLIC_API_URL=http://localhost:5000/api

"here is my .env file change the configuration according to it"